### ISSUE TITLE
Airflow: Our SQL check_null / check_unique tests fail when table is empty

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#1227]
I tried to add `check_null` and `check_unique` tests on `gtfs_views_staging.translations_clean`, which is an empty table, and I get this error, seemingly caused by this line: https://github.com/cal-itp/data-infra/blob/main/airflow/plugins/testing.py#L91 (shoutout @atvaccaro for pinning that down)

```
[2022-03-16 18:16:47,189] {logging_mixin.py:109} INFO - 
        CREATE OR REPLACE TABLE `gtfs_views_staging.translations_clean`
        
        AS -- Trim all string fields
-- Incoming schema explicitly defined in gtfs_schedule_history external table definition

SELECT
    calitp_itp_id
    , calitp_url_number
    , TRIM(table_name) as table_name
    , TRIM(field_name) as field_name
    , TRIM(language) as language
    , TRIM(translation) as translation
    , TRIM(record_id) as record_id
    , TRIM(record_sub_id) as record_sub_id
    , TRIM(field_value) as field_value
    , calitp_extracted_at
    , calitp_hash
    , FARM_FINGERPRINT(CONCAT(CAST(calitp_hash AS STRING), "___", CAST(calitp_extracted_at AS STRING))) AS translation_key
    , COALESCE(calitp_deleted_at, "2099-01-01") AS calitp_deleted_at
FROM `gtfs_schedule_type2.translations`
[2022-03-16 18:16:49,266] {sql_to_warehouse_operator.py:40} INFO - Query table as created successfully
[2022-03-16 18:16:51,462] {logging_mixin.py:109} INFO - {'check_null': ['calitp_hash', 'translation_key'], 'check_unique': ['translation_key']}
[2022-03-16 18:16:54,718] {taskinstance.py:1463} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1165, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1283, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1313, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/gcs/plugins/operators/sql_to_warehouse_operator.py", line 106, in execute
    get_engine(), format_table_name(table_name), self.tests
  File "/opt/airflow/gcs/plugins/testing.py", line 167, in from_tests
    test_func(fields)
  File "/opt/airflow/gcs/plugins/testing.py", line 120, in check_null
    query_template=null_query_template,
  File "/opt/airflow/gcs/plugins/testing.py", line 91, in run_test
    "nb_passed": len(results[results.passed]),
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 2896, in __getitem__
    if com.is_bool_indexer(key):
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/core/common.py", line 134, in is_bool_indexer
    raise ValueError(na_msg)
ValueError: Cannot mask with non-boolean array containing NA / NaN values
```

We should make these tests able to handle empty tables.

**Comment by lauriemerrell** [comment]
Closing as obsolete in v2, we no longer do these kinds of SQL tests in Airflow.
