### ISSUE TITLE
Bug: DBT build error during PRs dbt checks

### ISSUE THREAD

**Issue by vevetron** [cal-itp/data-infra#3433]
**Describe the bug**

Seen an error for a few different prs recently during the build phase:

https://github.com/cal-itp/data-infra/actions/runs/10726892913/job/29747950524

`
Writing to target/report.md
***"code":"ERR_INVALID_URL","input":"***\"message\": \"Request Too Long\"***","level":"error","message":"Invalid URL","stack":"TypeError [ERR_INVALID_URL]: Invalid URL\n    at new NodeError (node:internal/errors:387:5)\n    at URL.onParseError (node:internal/url:565:9)\n    at new URL (node:internal/url:641:5)\n    at uriParam (/opt/hostedtoolcache/node/16.20.2/x64/lib/node_modules/@dvcorg/cml/src/utils.js:149:15)\n    at watermarkUri (/opt/hostedtoolcache/node/16.20.2/x64/lib/node_modules/@dvcorg/cml/src/utils.js:140:10)\n    at CML.publish (/opt/hostedtoolcache/node/16.20.2/x64/lib/node_modules/@dvcorg/cml/src/cml.js:351:13)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async visitor (/opt/hostedtoolcache/node/16.20.2/x64/lib/node_modules/@dvcorg/cml/src/cml.js:249:26)\n    at async Promise.all (index 0)\n    at async publishLocalFiles (/opt/hostedtoolcache/node/16.20.2/x64/lib/node_modules/@dvcorg/cml/src/cml.js:263:7)"***
`

**To Reproduce**
Start a pr that does dbt stuff.

**Expected behavior**
Everything is awesome 
![image](https://media1.tenor.com/m/m01eD_cUIZQAAAAC/everything-is-awesome-good-mood.gif)

**Comment by vevetron** [comment]
From what I can tell, we didn't do anything and this error just went away.

**Comment by vevetron** [comment]
It's coming back recently on some prs, not sure of the pattern: https://github.com/cal-itp/data-infra/pull/3770
