### ISSUE TITLE
gtfs-downloader failing

### ISSUE THREAD

**Issue by hunterowens** [cal-itp/data-infra#46]
@machow looks like there's another prod / dev mismatch 

```
--------------------------------------------------------------------------------
[2021-04-01 00:02:56,212] {taskinstance.py:902} INFO - Executing <Task(PythonOperator): generate_provider_list> on 2021-03-31T00:00:00+00:00
[2021-04-01 00:02:56,216] {standard_task_runner.py:54} INFO - Started process 18564 to run task
[2021-04-01 00:02:56,276] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'gtfs_downloader', 'generate_provider_list', '2021-03-31T00:00:00+00:00', '--job_id', '14606', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/dags.py', '--cfg_path', '/tmp/tmpxfem0oy2']
[2021-04-01 00:02:56,277] {standard_task_runner.py:78} INFO - Job 14606: Subtask generate_provider_list
[2021-04-01 00:02:57,993] {logging_mixin.py:112} INFO - Running <TaskInstance: gtfs_downloader.generate_provider_list 2021-03-31T00:00:00+00:00 [running]> on host airflow-worker-759f6bc4d6-qpzhg
[2021-04-01 00:02:58,104] {taskinstance.py:1152} ERROR - 'DAG_DIRECTORY'
Traceback (most recent call last)
  File "/usr/local/lib/airflow/airflow/models/taskinstance.py", line 985, in _run_raw_tas
    result = task_copy.execute(context=context
  File "/usr/local/lib/airflow/airflow/operators/python_operator.py", line 113, in execut
    return_value = self.execute_callable(
  File "/usr/local/lib/airflow/airflow/operators/python_operator.py", line 118, in execute_callabl
    return self.python_callable(*self.op_args, **self.op_kwargs
  File "/home/airflow/gcs/dags/gtfs_downloader/generate_provider_list.py", line 54, in gen_lis
    provider_set = make_gtfs_list().apply(clean_url
  File "/home/airflow/gcs/dags/gtfs_downloader/generate_provider_list.py", line 22, in make_gtfs_lis
    fname = pipe_file_name("data/agencies.yml"
  File "/home/airflow/gcs/plugins/calitp.py", line 27, in pipe_file_nam
    root = Path(os.environ["DAG_DIRECTORY"]).paren
  File "/opt/python3.6/lib/python3.6/os.py", line 669, in __getitem_
    raise KeyError(key) from Non
KeyError: 'DAG_DIRECTORY
[2021-04-01 00:02:58,107] {taskinstance.py:1196} INFO - Marking task as FAILED. dag_id=gtfs_downloader, task_id=generate_provider_list, execution_date=20210331T000000, start_date=20210401T000255, end_date=20210401T000258
[2021-04-01 00:02:58,986] {sendgrid.py:116} INFO - Email with subject Airflow alert: <TaskInstance: gtfs_downloader.generate_provider_list 2021-03-31T00:00:00+00:00 [failed]> is successfully sent to recipients: [{'to': [{'email': 'hunter.owens@dot.ca.gov'}]}]@-@{"workflow": "gtfs_downloader", "task-id": "generate_provider_list", "execution-date": "2021-03-31T00:00:00+00:00"}
[2021-04-01 00:03:00,695] {local_task_job.py:102} INFO - Task exited with return code 1

```

**Comment by machow** [comment]
Hmm.. I shelled into cloud composer and apparently the env variable should be DAGS_FOLDER. Will open a quick PR / merge, so I can make sure everything is working..
