### ISSUE TITLE
Investigate HTTP connection pool error w/ Humbolt / Trinity feeds

### ISSUE THREAD

**Issue by hunterowens** [cal-itp/data-infra#56]

**Comment by hunterowens** [comment]
This appears to be taking down the entire task 
```
[2021-04-13 00:07:17,520] {taskinstance.py:1152} ERROR - HTTPSConnectionPool(host='data.trilliumtransit.com', port=443): Max retries exceeded with url: /gtfs/cudahy-ca-us/cudahy-ca-us.zip (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc67a748400>: Failed to establish a new connection: [Errno 110] Connection timed out',))
Traceback (most recent call last)
  File "/opt/python3.6/lib/python3.6/site-packages/urllib3/connection.py", line 160, in _new_con
    (self._dns_host, self.port), self.timeout, **extra_k
  File "/opt/python3.6/lib/python3.6/site-packages/urllib3/util/connection.py", line 84, in create_connectio
    raise er
  File "/opt/python3.6/lib/python3.6/site-packages/urllib3/util/connection.py", line 74, in create_connectio
    sock.connect(sa
TimeoutError: [Errno 110] Connection timed ou

During handling of the above exception, another exception occurred

Traceback (most recent call last)
  File "/opt/python3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlope
    chunked=chunked
  File "/opt/python3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 381, in _make_reques
    self._validate_conn(conn
  File "/opt/python3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 978, in _validate_con
    conn.connect(
  File "/opt/python3.6/lib/python3.6/site-packages/urllib3/connection.py", line 309, in connec
    conn = self._new_conn(
  File "/opt/python3.6/lib/python3.6/site-packages/urllib3/connection.py", line 172, in _new_con
    self, "Failed to establish a new connection: %s" % 
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fc67a748400>: Failed to establish a new connection: [Errno 110] Connection timed ou

During handling of the above exception, another exception occurred

Traceback (most recent call last)
  File "/opt/python3.6/lib/python3.6/site-packages/requests/adapters.py", line 449, in sen
    timeout=timeou
  File "/opt/python3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 727, in urlope
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2
  File "/opt/python3.6/lib/python3.6/site-packages/urllib3/util/retry.py", line 446, in incremen
    raise MaxRetryError(_pool, url, error or ResponseError(cause)
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='data.trilliumtransit.com', port=443): Max retries exceeded with url: /gtfs/cudahy-ca-us/cudahy-ca-us.zip (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc67a748400>: Failed to establish a new connection: [Errno 110] Connection timed out',)

During handling of the above exception, another exception occurred

Traceback (most recent call last)
  File "/usr/local/lib/airflow/airflow/models/taskinstance.py", line 985, in _run_raw_tas
    result = task_copy.execute(context=context
  File "/usr/local/lib/airflow/airflow/operators/python_operator.py", line 113, in execut
    return_value = self.execute_callable(
  File "/usr/local/lib/airflow/airflow/operators/python_operator.py", line 118, in execute_callabl
    return self.python_callable(*self.op_args, **self.op_kwargs
  File "/home/airflow/gcs/dags/gtfs_downloader/download_data.py", line 96, in downloade
    execution_date
  File "/home/airflow/gcs/dags/gtfs_downloader/download_data.py", line 52, in download_ur
    r = requests.get(url, headers=headers
  File "/opt/python3.6/lib/python3.6/site-packages/requests/api.py", line 76, in ge
    return request('get', url, params=params, **kwargs
  File "/opt/python3.6/lib/python3.6/site-packages/requests/api.py", line 61, in reques
    return session.request(method=method, url=url, **kwargs
  File "/opt/python3.6/lib/python3.6/site-packages/requests/sessions.py", line 542, in reques
    resp = self.send(prep, **send_kwargs
  File "/opt/python3.6/lib/python3.6/site-packages/requests/sessions.py", line 655, in sen
    r = adapter.send(request, **kwargs
  File "/opt/python3.6/lib/python3.6/site-packages/requests/adapters.py", line 516, in sen
    raise ConnectionError(e, request=request
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='data.trilliumtransit.com', port=443): Max retries exceeded with url: /gtfs/cudahy-ca-us/cudahy-ca-us.zip (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc67a748400>: Failed to establish a new connection: [Errno 110] Connection timed out',)
[2021-04-13 00:07:17,526] {taskinstance.py:1196} INFO - Marking task as FAILED. dag_id=gtfs_downloader, task_id=download_data, execution_date=20210412T000000, start_date=20210413T000548, end_date=20210413T000717
[2021-04-13 00:07:20,143] {sendgrid.py:116} INFO - Email with subject Airflow alert: <TaskInstance: gtfs_downloader.download_data 2021-04-12T00:00:00+00:00 [failed]> is successfully sent to recipients: [{'to': [{'email': 'hunter.owens@dot.ca.gov'}]}]@-@{"workflow": "gtfs_downloader", "task-id": "download_data", "execution-date": "2021-04-12T00:00:00+00:00"}
[2021-04-13 00:07:24,053] {local_task_job.py:102} INFO - Task exited with return code 1
```

**Comment by machow** [comment]
should be resolved!
